# Dockerfile for multi-server profiling tests.
# Builds off of "base" profiling image, configures FreeRADIUS and builds it.
FROM freeradius4-default-profiling/ubuntu24:latest

RUN ./configure \
    --enable-developer \
    --disable-verify-ptr \
    --with-raddbdir=/etc/freeradius \
    CFLAGS="-g3 -O1 -fno-omit-frame-pointer" \
    LDFLAGS="-fno-omit-frame-pointer"

RUN make

# FreeRADIUS installed in /etc/freeradius
RUN make install

# Generate the self-signed RSA (and DH/EC) certificates for testing.
RUN cd /etc/freeradius/certs && make


